name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch: null 
permissions: write-all
env:
  EKS_CLUSTER_NAME: cicd-cluster
  AWS_REGION: us-east-1
  DOCKER_REPOSITORY: goapp


jobs:
  deploy:
    runs-on: ubuntu-latest

    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: actions-hub/kubectl@v1

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install my-release ./my-chart --namespace my-namespace --set image.tag=${{ github.sha }}











